name: Fabric Deployment Pipeline

on:
  push:
    branches:
      - main

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  PIPELINE_ID: ${{ secrets.PIPELINE_ID }}

jobs:
  validate-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Dev Workspace
        run: echo "Validating Dev workspace..."

  deploy-uat:
    needs: validate-dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to UAT
        run: |
          token=$(curl -X POST -d "grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&resource=https://analysis.windows.net/powerbi/api" https://login.microsoftonline.com/$TENANT_ID/oauth2/token | jq -r '.access_token')
          curl -X POST https://api.powerbi.com/v1.0/myorg/deploymentPipelines/$PIPELINE_ID/deploy \
            -H "Authorization: Bearer $token"

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Manual approval
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Prod
        run: |
          token=$(curl -X POST -d "grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&resource=https://analysis.windows.net/powerbi/api" https://login.microsoftonline.com/$TENANT_ID/oauth2/token | jq -r '.access_token')
          curl -X POST https://api.powerbi.com/v1.0/myorg/deploymentPipelines/$PIPELINE_ID/deploy \
            -H "Authorization: Bearer $token"
